AndreLanches/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace AndreLanches.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Contato()
        {
            return View();
        }
    }
}

AndreLanches/Controllers/LancheController.cs
using AndreLanches.Models;
using AndreLanches.Repositories.Interfaces;
using AndreLanches.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AndreLanches.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult LancheList(string categoria)
        {
            IEnumerable<LancheModel> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches
                    .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }
            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
            return View(lanche);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<LancheModel> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.LancheId);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches
                          .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));

                if (lanches.Any())
                    categoriaAtual = "Lanches";
                else
                    categoriaAtual = "Nenhum lanche foi encontrado";
            }

            return View("~/Views/Lanche/LancheList.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            });
        }
    }
}

AndreLanches/Views/Shared/_Barra.cshtml
 <header>
         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/lanchemac2.png" widht="100" height="100" />
                    André Lanches
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav navbar-right">
                       <li>@await Component.InvokeAsync("CarrinhoCompraResumo")</li>
                       <li>@await Component.InvokeAsync("CategoriaMenu")</li>
                       <li><a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Contato">Contato</a></li>
                       <li><a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                       <li>
                        <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                          <div class="form-group">
                            <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                          </div>
                        </form>
                        </li>
                        <li>
                        @await Html.PartialAsync("_LoginPartial")
                        </li>
                        <li>
                        @if(User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                        }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

AndreLanches/Views/Shared/_BarraMenu.cshtml
 <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/lanchemac2.png" widht="100" height="100" />
                    André Lanches
                </a>
     <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"
     aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
      <!-- Collapsible content -->
    <div class="navbar-collapse collapse" id="collapsibleNavbar" style="font-size: medium; font-weight: bold">
           <ul class="navbar-nav mr-auto">
               <li class="nav-item">@await Component.InvokeAsync("CategoriaMenu")</li>
                <li class="nav-item">
                  <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                    <div class="form-group">
                       <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                    </div>
                 </form>
                </li>
               <li class="nav-item"><a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Contato">Contato</a></li>
               <li class="nav-item"><a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
               <li class="nav-item">
                 @if(User.IsInRole("Admin"))
                 {
                    <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                 }
               </li>
              <li class="nav-item">@await Html.PartialAsync("_LoginPartial")</li>
              <li class="nav-item">@await Component.InvokeAsync("CarrinhoCompraResumo")</li>
          </ul>
    </div>
  </div>
 </nav>

AndreLanches/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/carousel11.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel12.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel13.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

AndreLanches/Views/Shared/_Footer.cshtml
<footer>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
     <div class="container">
         <div class="row">
             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4> &copy; 2022 - AndreLanches</h4>
                 <p class="text-justify">
                     Aqui você encontra aquele lanche gostoso que da água na boca.
                     Aquela sobremesa saborosa e para acompanhar a sua bebida preferida.
                     E se você é vegetariano também vai encontrar o lanche, sobremesa e bebida do seu gosto.
                 </p>
             </div>

             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4>Tem alguma dúvida ?</h4>
                 <ul class="list-unstyled">
                     <li class="py-1"> Av. Bueno de Andrade, 56 Setor-2 Quadra-7</li>
                     <li class="py-1"> +55 11 94875-8417</li>
                     <li class="py-1"> <a href="andresantos216@gmail.com" style="color: yellow">andresantos216@gmail.com</a></li>
                 </ul>
             </div>
         </div>
     </div>
    </nav>
</footer>

AndreLanches/Views/Shared/_LanchesResumo.cshtml
@model LancheModel

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid"></p>
    <h3>Preço : @Model.Preco.ToString("c")</h3>

    <h4>
    <a asp-controller="Lanche" asp-action="Details" 
    asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
    </h4>

    <p>@Model.DescricaoCurta</p>
      <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" 
            asp-action="AdicionarItemNoCarrinhoCompra" asp-route-LancheId="@Model.LancheId">
            Incluir no Carrinho
        </a>
        </p>
    </div>

</div>

AndreLanches/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AndreLanches</title>
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AndreLanches.styles.css" asp-append-version="true" />
</head>

<body>
@*    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/lanchemac2.png" widht="100" height="100" />
                    André Lanches
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    @await Component.InvokeAsync("CategoriaMenu")
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Contato">Contato</a>
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                      <div class="form-group">
                        <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                      </div>
                    </form>
                    @await Html.PartialAsync("_LoginPartial")
                    @if(User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }
                </div>
            </div>
        </nav>
    </header>*@

    <div>
         <partial name="_BarraMenu.cshtml" />
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AndreLanches
        </div>
    </footer>*@


    <div>
     <partial name="_Footer"/>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>